export const TableData:Array<any> = [
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample HTML5 multi-axis column chart from Domain showing Sales, Units, and $ Per Square Foot by Country and Store Type with various filters. Created from an Ad Hoc View.",
      "label": "01. Geographic Results by Segment Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-14T10:46:00",
      "uri": "/public/Samples/Reports/01._Geographic_Results_by_Segment_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample HTML5 Spider Line chart from OLAP source. Created from an Ad Hoc View.",
      "label": "02. Sales Mix by Demographic Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-25T09:05:59",
      "uri": "/public/Samples/Reports/02._Sales_Mix_by_Demographic_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample OLAP chart with HTML5 Grouped Bar chart and Filter. Created from an Ad Hoc View.",
      "label": "03. Store Segment Performance Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-25T09:06:57",
      "uri": "/public/Samples/Reports/03._Store_Segment_Performance_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample Filtered Table Report Showing Multiple Measures. Created from Sample Ad Hoc View.",
      "label": "04. Product Results by Store Type Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-15T17:06:02",
      "uri": "/public/Samples/Reports/04._Product_Results_by_Store_Type_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Basic interactive Table Component report with Bookmarks Panel",
      "label": "05. Accounts Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-17T10:07:12",
      "uri": "/public/Samples/Reports/AllAccounts",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Basic interactive Table Component report with alternate color scheme.",
      "label": "05g. Accounts Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2013-10-03T16:17:06",
      "uri": "/public/Samples/Reports/5g.AccountsReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "06. Profit Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:28:15",
      "uri": "/public/Samples/Reports/ProfitDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "06g. Profit Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:28:56",
      "uri": "/public/Samples/Reports/06g.ProfitDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "07. Revenue Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:29:17",
      "uri": "/public/Samples/Reports/RevenueDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "07g. Revenue Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:29:39",
      "uri": "/public/Samples/Reports/07g.RevenueDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "08. Unit Sales Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:29:57",
      "uri": "/public/Samples/Reports/08.UnitSalesDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample report containing containing interactive  HTML5 Chart and Table data with input controls. This report is also defined as a drill-down from the SuperMart Dashboard gauge.",
      "label": "08g. Unit Sales Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:30:15",
      "uri": "/public/Samples/Reports/08g.UnitSalesDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Sample report with multiple charts, interactive table, and input controls. Also called as drill-through from the SuperMart and Performance Summary Dashboards.",
      "label": "09. Customer Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:30:29",
      "uri": "/public/Samples/Reports/9.CustomerDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Sample report with multiple charts, interactive table, and input controls. Also called as drill-through from the SuperMart and Performance Summary Dashboards.",
      "label": "09g. Customer Detail Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:30:43",
      "uri": "/public/Samples/Reports/9g.CustomerDetailReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample report with Pie Chart and crosstab showing sales performance by store type and product category.",
      "label": "10. Performance By Store Type",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:36:19",
      "uri": "/public/Samples/Reports/State_Performance",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Sample report with Pie Chart and crosstab showing sales performance by store type and product category.",
      "label": "10g. Performance By Store Type",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:31:13",
      "uri": "/public/Samples/Reports/10g.PerformanceByStoreType",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Used in the Supermart dashboard.",
      "label": "11. Sales By Month Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2013-09-25T04:48:31",
      "uri": "/public/Samples/Reports/SalesByMonthReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Used in the Supermart alternate color scheme dashboard.",
      "label": "11g. Sales By Month Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:31:40",
      "uri": "/public/Samples/Reports/11g.SalesByMonthReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Drill-through from the Supermart dashboard.",
      "label": "12. Promotion Details Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:31:55",
      "uri": "/public/Samples/Reports/PromotionDetailsReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:19",
      "description": "Drill-through from the Supermart dashboard with alternate color scheme.",
      "label": "12g. Promotion Details Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:32:10",
      "uri": "/public/Samples/Reports/12g.PromotionDetailsReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:17",
      "description": "Top five customers, products, and promotions. Used in the Supermart Dashboard.",
      "label": "13. Top Fives Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-09-07T09:48:40",
      "uri": "/public/Samples/Reports/TopFivesReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Top five customers, products, and promotions. Used in the Supermart Dashboard with alternate color scheme.",
      "label": "13g. Top Fives Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2013-10-03T16:25:05",
      "uri": "/public/Samples/Reports/13g.TopFivesReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Report used for Performance Summary Dashboard.",
      "label": "14. Performance Summary",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:32:53",
      "uri": "/public/Samples/Reports/14.PerformanceSummary",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:17",
      "description": "Report used for Performance Summary Dashboard.",
      "label": "14. Stop Light KPI",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-11-06T16:55:43",
      "uri": "/public/Samples/Reports/14._Stop_Light_KPI",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:17",
      "description": "Report used for Performance Summary Dashboard.",
      "label": "14. World Map",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-09-08T17:35:54",
      "uri": "/public/Samples/Reports/14._World_Map",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Report used for Performance Summary Dashboard with alternate color scheme.",
      "label": "14g. Performance Summary",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:33:17",
      "uri": "/public/Samples/Reports/14g.PerformanceSummary",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Meter Gauges used in the Supermart Dashboard.",
      "label": "15. Sales Gauges Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2013-09-16T04:41:40",
      "uri": "/public/Samples/Reports/SalesGaugesReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Meter Gauges used in the Supermart Dashboard with alternate color scheme.",
      "label": "15g. Sales Gauges Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-13T16:33:39",
      "uri": "/public/Samples/Reports/15g.SalesGaugesReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Interactive table and chart.",
      "label": "16. Interactive Sales Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2015-11-13T14:45:40",
      "uri": "/public/Samples/Reports/Cascading_Report_2_Updated",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Interactive table and chart with alternate color scheme.",
      "label": "16g. Interactive Sales Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2015-11-13T14:45:53",
      "uri": "/public/Samples/Reports/16g.InteractiveSalesReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Sample report book with table of contents.",
      "label": "17. Report Workbook",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2015-10-27T10:55:44",
      "uri": "/public/Samples/Reports/17._Report_Workbook",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Sample Report used for basic Visualize.js demo",
      "label": "20.1 Account List",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-05-16T08:17:01",
      "uri": "/public/Samples/Reports/AccountList",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample Report used for basic Visualize.js demo",
      "label": "20.2 Cities",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-24T14:12:34",
      "uri": "/public/Samples/Reports/Cities",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:20",
      "description": "Sample Report created from Ad Hoc View for Basic Visualize.js Demo",
      "label": "20.3 SalesPerCityReport",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-24T14:21:45",
      "uri": "/public/Samples/Reports/20.3_SalesPerCityReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample Report used for basic Visualize.js demo",
      "label": "20.4 States",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-24T14:14:15",
      "uri": "/public/Samples/Reports/States",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample Report used for basic Visualize.js demo",
      "label": "20.5 StatesJFC",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-24T14:14:28",
      "uri": "/public/Samples/Reports/StatesJFC",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "Sample Report used for basic Visualize.js demo",
      "label": "20.6 Store Details",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2014-04-24T14:14:41",
      "uri": "/public/Samples/Reports/StoreDetails",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "All Accounts Report",
      "label": "All Accounts Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/AllAccounts",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "",
      "label": "Analysis of Product Sales by City Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2015-04-30T01:38:15",
      "uri": "/organizations/organization_1/reports/interactive/Analysis_of_Product_Sales_by_City_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "All events report",
      "label": "Archived Audit Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:22",
      "uri": "/public/audit/reports/archive/Audit_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "Audit crosstab report",
      "label": "Archived Performance Crosstab Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:28",
      "uri": "/public/audit/reports/archive/Performance_Crosstab_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "Performance Audit Report",
      "label": "Archived Performance Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:31",
      "uri": "/public/audit/reports/archive/Performance_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "Audit Report",
      "label": "Archived Repository Resources Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:34",
      "uri": "/public/audit/reports/archive/Repository_Resources_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "Audit Report",
      "label": "Archived Resource Execution Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:38",
      "uri": "/public/audit/reports/archive/Resource_Execution_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": "Audit Report",
      "label": "Archived User Activity Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:44",
      "uri": "/public/audit/reports/archive/User_Activity_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:14",
      "description": "All events report",
      "label": "Audit Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:49",
      "uri": "/public/audit/reports/Audit_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:28",
      "description": null,
      "label": "BlankBackground",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2013-09-06T03:56:37",
      "uri": "/public/Samples/Resources/Extras/BlankBackground",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Shows cascading input controls. Multi-select and single select queries",
      "label": "Cascading multi select topic",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/Cascading_multi_select_topic",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Parameterized Report with no default values for parameters",
      "label": "Customers Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/CustomersReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:27",
      "description": "Customers Report",
      "label": "Customers Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:49",
      "uri": "/organizations/organization_1/reports/interactive/CustomersReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Topic containing shipping costs for orders",
      "label": "demo for adhoc",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/AdhocDemo",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:12",
      "description": null,
      "label": "Diagnostic Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-10-17T16:30:38",
      "uri": "/public/diagnostic/JSDiagnosticReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:14",
      "description": "",
      "label": "Diagnostic Topic",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-09-26T10:59:42",
      "uri": "/public/adhoc/topics/JSDiagnosticTopic",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Employee List topic based on Employee List report in /Reports/Samples folder",
      "label": "Employees",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/Employees",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:21",
      "description": "foodmart data for crosstab",
      "label": "foodmart data for crosstab",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-10-15T09:33:18",
      "uri": "/public/Samples/Topics/CrosstabDemo",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "foodmart data for crosstab",
      "label": "foodmart data for crosstab",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/CrosstabDemo",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "Report with Mondrian Datasource",
      "label": "Foodmart Mondrian Sales Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:49",
      "uri": "/organizations/organization_1/analysis/reports/FoodmartSalesMondrianReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Columns are Internationalizable.<br>Default support for English, French, German, Japanese, and Spanish.<br>To add support for more languages add Resource Bundles to this topic",
      "label": "i18n columns",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/i18nColumns",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:27",
      "description": "Map Report",
      "label": "Map Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:50",
      "uri": "/organizations/organization_1/reports/interactive/MapReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Example of topic with MDX query",
      "label": "MDX example",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/MDXExample",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "MDX Frequency Report",
      "label": "MDX Frequency",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:50",
      "uri": "/organizations/organization_1/performance/reports/mdxFrequency",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:25",
      "description": "Parameterized Report",
      "label": "Parameterized Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/ShippingParam",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:14",
      "description": "Audit crosstab report",
      "label": "Performance Crosstab Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:53",
      "uri": "/public/audit/reports/Performance_Crosstab_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:14",
      "description": "Performance Audit Report",
      "label": "Performance Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:51:57",
      "uri": "/public/audit/reports/Performance_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:30",
      "description": "",
      "label": "Product Sales Trend",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2015-04-30T02:26:12",
      "uri": "/organizations/organization_1/reports/interactive/Analysis/Product_Sales_Trend",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "Query Timings Report",
      "label": "Query Timings",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:50",
      "uri": "/organizations/organization_1/performance/reports/queryTimings",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:15",
      "description": "The Report Monitoring Details report",
      "label": "Report Monitoring Details Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-11-02T22:22:08",
      "uri": "/public/monitoring/reports/Report_Monitoring_Details_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:15",
      "description": "The Report Monitoring Resources report",
      "label": "Report Monitoring Resources Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-11-02T22:45:17",
      "uri": "/public/monitoring/reports/Report_Monitoring_Resources_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:15",
      "description": "Audit Report",
      "label": "Repository Resources Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:52:01",
      "uri": "/public/audit/reports/Repository_Resources_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:15",
      "description": "Audit Report",
      "label": "Resource Execution Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:52:05",
      "uri": "/public/audit/reports/Resource_Execution_Report",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "SQL Frequency Report",
      "label": "SQL Frequency",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:50",
      "uri": "/organizations/organization_1/performance/reports/sqlFrequency",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "Information about all of the products sold by SuperMart",
      "label": "SuperMart Products",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/SuperMartProductsTopic",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:26",
      "description": "Simple Topic. Good for trying calculations (sales - cost = profit). Add summaries for sales and profit. Group by State, then show Chart.",
      "label": "SuperMart Stores",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:32:07",
      "uri": "/organizations/organization_1/adhoc/topics/SuperMartStoresTopic",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:27",
      "description": "Table Report",
      "label": "Table Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2017-10-31T12:31:50",
      "uri": "/organizations/organization_1/reports/interactive/TableReport",
      "version": "0"
  },
  {
      "creationDate": "2017-11-29T10:34:15",
      "description": "Audit Report",
      "label": "User Activity Report",
      "permissionMask": "1",
      "resourceType": "reportUnit",
      "selectable": false,
      "updateDate": "2012-05-03T16:52:10",
      "uri": "/public/audit/reports/User_Activity_Report",
      "version": "0"
  }
];